# NOTE: We're using both Travis CI and Github Actions, if you change this file,
# also change .travis.yml accordingly.
name: ci

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} (${{ matrix.compiler }})

    strategy:
      fail-fast: false
      matrix:
        include:
          # - name: Linux
          #   os: ubuntu-20.04  # -latest is still stuck at 18.04
          #   compiler: gcc
          #   cpp-compiler: g++

          # - name: Linux
          #   os: ubuntu-20.04  # -latest is still stuck at 18.04
          #   compiler: clang
          #   cpp-compiler: clang++

          - name: Linux
            os: ubuntu-20.04  # -latest is still stuck at 18.04
            compiler: mingw64
            cpp-compiler: mingw64

          # - name: Windows
          #   os: windows-latest
          #   packages: ccache
          #   compiler: cl
          #   cpp-compiler: cl
          #   cmake-args: -A Win32
          #   build-args: "/clp:NoSummary"

          # - name: macOS
          #   os: macOS-latest
          #   packages: yaml-cpp sdl sdl_gfx sdl_image sdl_mixer
          #   # cmake-args: -DCMAKE_BINARY_DIR=/usr/local/bin
          #   compiler: clang
          #   cpp-compiler: clang++
          #   app-bundle: openxcom.app  # all other builds default to bin/

    runs-on: ${{ matrix.os }}

    steps:
      # - name: Set up MinGW
      #   if: matrix.compiler == 'mingw64'
      #   uses: egor-tensin/setup-mingw@v2
      #   with:
      #     platform: x64

      - name: Install packages (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get -yq --no-install-suggests --no-install-recommends install ccache ${{ matrix.packages }}
          sudo apt-get -yq --no-install-suggests --no-install-recommends install libsdl1.2-dev libsdl-mixer1.2-dev libsdl-image1.2-dev libsdl-gfx1.2-dev libyaml-cpp-dev

      - name: Install packages (Ubuntu/mingw)
        if: matrix.compiler == 'mingw64'
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 86B72ED9
          sudo add-apt-repository "deb [arch=amd64] https://pkg.mxe.cc/repos/apt `lsb_release -sc` main"
          sudo apt-get update
          sudo apt-get install mxe-x86-64-w64-mingw32.static-cc mxe-x86-64-w64-mingw32.static-cmake

      - name: Install packages (Windows)
        if: runner.os == 'Windows' && matrix.packages
        run: |
          choco install ${{ matrix.packages }}

      - name: Install packages (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install ccache ${{ matrix.packages }}

      - name: Setup Cache
        if: runner.os == 'Linux' || runner.os == 'macOS' || runner.os == 'Windows'
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ccache-${{ runner.os }}-${{ matrix.compiler }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup environment
        shell: bash
        run: |
          echo "describe=$(git describe)" >> $GITHUB_ENV
          if [ "${{ matrix.name }}" = "Linux" ]; then
            echo "MAYBE_SUDO=sudo" >> $GITHUB_ENV
          fi
          echo "CMAKE_BUILD_PARALLEL_LEVEL=`getconf _NPROCESSORS_ONLN 2>/dev/null || getconf NPROCESSORS_ONLN 2>/dev/null || echo 2`" >> $GITHUB_ENV

      - name: Download dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          Invoke-WebRequest -Uri "https://openxcom.org/download/dev/openxcom-deps-win-vc2017.zip" -OutFile "openxcom-deps-win-vc2017-newest.zip"
          Expand-Archive -Path "openxcom-deps-win-vc2017-newest.zip" -DestinationPath "."

      - name: Download dependencies (mingw)
        if: matrix.compiler == 'mingw64'
        run: |
          wget -q "https://openxcom.org/download/dev/openxcom-deps-win-vc2017.zip"
          unzip openxcom-deps-win-vc2017.zip

      - name: Generate project files
        if: matrix.compiler != 'mingw64'
        run: |
          echo "CMAKE=$(which cmake)" >> $GITHUB_ENV
          cmake -B ${{ matrix.build-dir || 'build' }} ${{ matrix.build-src-dir || '.' }} -DCMAKE_BUILD_TYPE=Release -DENABLE_WARNING=1 -DCHECK_CCACHE=1 ${{ matrix.cmake-args }}
        env:
          CC: ${{ matrix.compiler }}
          CXX: ${{ matrix.cpp-compiler }}

      - name: Generate project files (mingw)
        if: matrix.compiler == 'mingw64'
        run: |
          GITISODATE=$(git show -s --format=%ci)
          GITDATE=$(date -d"$GITISODATE" +%Y-%m-%d)
          GITREF=$(git show -s --format=%h)
          OSARCH=win64
          SHORTVERSION=$(/bin/echo -e "#include \"src/version.h\"\nOPENXCOM_FTA_VERSION_SHORT" | cpp | egrep -v '^(#.+|[[:space:]]+$)' | cut -d\" -f 2 | sed -e "s, ,-,g")
          ZNAME="$SHORTVERSION-$GITREF-$GITDATE-$OSARCH.7z"
          export PATH=/usr/lib/mxe/usr/bin:$PATH
          # export PATH=/opt/mxe/usr/bin:$PATH

          TOOLCHAIN=/usr/lib/mxe/usr/bin/x86_64-w64-mingw32.static

          echo "CMAKE=$TOOLCHAIN-cmake" >> $GITHUB_ENV

          mkdir build iprefix
          cd build
          ${TOOLCHAIN}-cmake \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo -DDEV_BUILD=OFF -DBUILD_PACKAGE=OFF \
            -DCMAKE_INSTALL_PREFIX=../iprefix ..

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          limit-access-to-actor: true

      - name: Compile source code
        # if: matrix.compiler != 'mingw64'
        run: |
          $CMAKE --build ${{ matrix.build-dir || 'build' }} -v --config ${{ matrix.build-config || 'Release' }} -- ${{ matrix.build-args }}

#      - name: Fix install path
#        if: runner.os == 'macOS'
#        shell: bash
#        run: |
#          echo "CMAKE_BINARY_DIR=/usr/local/bin" >> $GITHUB_ENV

        # Note, this is bogus on MacOS, as it installs shaders et al twice.
        # Windows installs under C:/Program Files (x86)/OpenXcom/bin (where the
        # 'bin' is pretty redundant) and Linux installs under various dirs under
        # /usr/local
      - name: Make install
        if: runner.os == 'Linux' || runner.os == 'macOS' || runner.os == 'Windows'
        shell: bash
        run: |
          $MAYBE_SUDO cmake --build ${{ matrix.build-dir || 'build' }} -v --config ${{ matrix.build-config || 'Release' }} --target install

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
            name: openxcom_${{ matrix.name }}_${{ matrix.compiler }}-${{ env.describe }}
            path: |
                ${{ matrix.build-dir || 'build' }}/${{ matrix.app-bundle || 'bin' }}/**/*

      - name: ccache stats
        if: runner.os == 'Linux' || runner.os == 'macOS' || runner.os == 'Windows'
        run: ccache -s --max-size=390MB
